name: "Update version in gradle properties"
description: "Composite action to update version in gradle properties"

inputs:
  version_name:
    description: "The version name to set (e.g., 1.3.0)."
    required: true
  gradle_properties_location:
    description: "Path to the Android gradle.properties file."
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Android Version in gradle.properties
      shell: bash
      run: |
        GRADLE_FILE="${{ inputs.gradle_properties_location }}"
        VERSION_NAME="${{ inputs.version_name }}"

        if [ ! -f "$GRADLE_FILE" ]; then
          echo "Error: gradle.properties file not found at $GRADLE_FILE"
          exit 1
        fi

        sed -i -e "s/version=.*/version=$VERSION_NAME/" "$GRADLE_FILE"

        echo "Updated gradle.properties with version=$VERSION_NAME"
